### ISSUE TITLE
Escape double quotes character while validating object name

### ISSUE THREAD

**Issue by anthioikonomou** [themost-framework/mssql#51]
Escape double quotes character at ObjectNameValidator class to support select statements as 

`select familyName as "Family Name" `

**Comment by kbarbounakis** [comment]
This feature -of using double quotes in alias- is supported from SQLite, PostgreSQL, MySQL, MSSQL etc and should be supported by `@themost/query#ObjectNameValidator` https://github.com/themost-framework/query/issues/106
